name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Frontend
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci && cd frontend && npm ci
      - name: Run tests
        run: cd frontend && npm test
        env:
          CI: true
